name: mfs_mobile
description: "Mobile version of AI-driven microfinance web app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  flutter_credit_card: ^4.1.0
  percent_indicator: ^4.2.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^16.0.0
  
  # Network
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.1.4
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  uuid: ^4.2.2
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2
  url_launcher: ^6.2.2
  image_picker: ^1.0.7

  # http dependency
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  mockito: ^5.4.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env